name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        release: false
        install: mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-qt6-base mingw-w64-ucrt-x86_64-make
          mingw-w64-ucrt-x86_64-libmariadbclient mingw-w64-ucrt-x86_64-postgresql
          mingw-w64-ucrt-x86_64-firebird mingw-w64-ucrt-x86_64-qt6-activeqt mingw-w64-ucrt-x86_64-qwt-qt6
        update: true
    - name: build
      shell: cmd
      run: |
        set PATH=%RUNNER_TEMP%\msys64\ucrt64\bin;%RUNNER_TEMP%\msys64\ucrt64\share\qt6\bin;C:\msys64\ucrt64\bin;C:\msys64\ucrt64\share\qt6\bin;%PATH%
        qmake6
        mingw32-make -j4
    - name: pack
      shell: cmd
      run: |
        set PATH=%RUNNER_TEMP%\msys64\ucrt64\bin;%RUNNER_TEMP%\msys64\ucrt64\share\qt6\bin;C:\msys64\ucrt64\bin;C:\msys64\ucrt64\share\qt6\bin;C:\Miniconda;C:\Miniconda\Scripts;%PATH%
        where mugideploy 1> NUL 2> NUL || pip install mugideploy
        mugideploy collect --bin release\main.exe --plugins sqldrivers
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: main-0.0.1-win64
        path: main-0.0.1-win64
