name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        where patch
        where gcc
        C:\mingw64\bin\gcc.exe -v
        C:\Strawberry\c\bin\gcc.exe -v
