name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: qtbase671
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Android\android-sdk\cmake\3.22.1\bin;%PATH%
        pip install mugicli
        if exist C:\Qt\6.7.2\mingw1220_64\bin\qmake.exe goto qtbase671_end
        move /y "C:\Program Files\PostgreSQL" "C:\Program Files\PostgreSQL_" || echo 1 > NUL
        move /y "C:\Program Files\MySQL" "C:\Program Files\MySQL_" || echo 1 > NUL
        move /y "C:\Program Files\OpenSSL" "C:\Program Files\OpenSSL_" || echo 1 > NUL
        move /y C:\Strawberry C:\Strawberry_ || echo 1 > NUL
        move /y C:\tools\php C:\tools\php_ || echo 1 > NUL
        if not exist qtbase-everywhere-src-6.7.2.zip curl -L -o qtbase-everywhere-src-6.7.2.zip https://download.qt.io/official_releases/qt/6.7/6.7.2/submodules/qtbase-everywhere-src-6.7.2.zip
        if not exist qtbase-everywhere-src-6.7.2 7z x -y qtbase-everywhere-src-6.7.2.zip
        pushd qtbase-everywhere-src-6.7.2
            cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:/Qt/6.7.2/mingw1220_64 -DQT_QMAKE_TARGET_MKSPEC=win32-g++ -DQT_BUILD_TESTS=FALSE -DQT_BUILD_EXAMPLES=FALSE -DFEATURE_system_zlib=OFF .
            ninja Qt6Core.dll
            ninja Qt6Gui.dll
            ninja Qt6Widgets.dll
            pyfind -iname *.dll *.exe *.a -stat | pysort > ..\stat1.txt
            pyfind -iname *.dll *.exe *.a *.obj -stat | pysort > ..\stat2.txt
        popd
        :qtbase671_end
    - name: main
      shell: cmd
      run: echo yes
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: stat1
        path: |
          stat1.txt
          stat2.txt
